language: node_js
# nodejs版本
node_js:
  - "stable"
# 缓存
cache:
  directories:
    - node_modules
env: -CI=true
install:
  - npm install
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token 
  local_dir: build # 需要将将哪个文件夹的文件上传
  on:
    branch: main  # 哪个branch有push时触发deploy
